package frc.robot.vision;

import edu.wpi.first.apriltag.AprilTagDetection;
import edu.wpi.first.apriltag.AprilTagDetector;
import edu.wpi.first.apriltag.AprilTagPoseEstimator;
import edu.wpi.first.cscore.CvSource;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.vision.VisionPipeline;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.opencv.core.*;
import org.opencv.imgproc.*;
import org.opencv.objdetect.Objdetect;

/**
* TestPipeline class.
*
* <p>An OpenCV pipeline generated by GRIP.
*
* @author GRIP
*/
public class TestPipeline implements VisionPipeline {

	private CvSource outputStream;

	private AprilTagDetector detector;
	private AprilTagPoseEstimator poseEstimator;

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	public TestPipeline() {
		// this.outputStream = outputStream;
		detector = new AprilTagDetector();
        detector.addFamily("tag36h11");

        AprilTagPoseEstimator.Config poseConfig =
            new AprilTagPoseEstimator.Config(
                Units.inchesToMeters(6.5), // Tag size (official FRC tag)
                546.6314297825006,         // fx
                547.4164926890426,         // fy
                333.04330891767796,        // cx
                243.95434359639907         // cy
            );

        poseEstimator =
            new AprilTagPoseEstimator(poseConfig);
	}

	/**
	 * This is the primary method that runs the entire pipeline and updates the outputs.
	 */
	@Override	public void process(Mat source0) {
		// Mat mat = source0.clone();
		Mat gray = new Mat();
		Imgproc.cvtColor(source0, gray, Imgproc.COLOR_BGR2GRAY);
		
		Dictionary dictionary = Objdetect.getPredefinedDictionary(Objdetect.DICT_APRILTAG_36h11);
		
		AprilTagDetection[] detections = detector.detect(gray);

		SmartDashboard.putNumber("# of Detections", detections.length);
		SmartDashboard.putString("Image shape", gray.size().toString());
		SmartDashboard.putNumber("Image dims", gray.dims());
		
		SmartDashboard.putString("I KNOW U WORK", "!!!!" + Math.random());
		String grayImgString = gray.get(0, 0)[0] + "," + gray.get(0, 1)[0] + "," + gray.get(0, 2)[0];
		SmartDashboard.putString("GRAY IMG", grayImgString);
		SmartDashboard.putString("GrayImgMetadata", gray.toString());
		// SmartDashboard.putNumberArray("gray img", pixelVals);
		
		// for (AprilTagDetection detection : detections) {
		// 	int id = detection.getId();

		// 	// Estimate pose
		// 	Transform3d pose = poseEstimator.estimate(detection);

		// 	// Draw outline
		// 	double[] cornersDoubleArr = detection.getCorners();
		// 	Point[] corners = new Point[4];
		// 	for (int i = 0; i < 4; i++) {
		// 		corners[i] = new Point(cornersDoubleArr[2 * i], cornersDoubleArr[2 * i + 1]);
		// 	}
		// 	for (int i = 0; i < 4; i++) {
		// 		Imgproc.line(
		// 			mat,
		// 			corners[i],
		// 			corners[(i + 1) % 4],
		// 			new Scalar(0, 255, 0),
		// 			2
		// 		);
		// 	}

		// 	// Draw ID
		// 	Imgproc.putText(
		// 		mat,
		// 		"ID " + id,
		// 		corners[0],
		// 		Imgproc.FONT_HERSHEY_SIMPLEX,
		// 		0.6,
		// 		new Scalar(0, 255, 0),
		// 		2
		// 	);

		// 	// Example: publish distance
		// 	SmartDashboard.putNumber(
		// 		"Tag " + id + " Z (m)",
		// 		pose.getZ()
		// 	);
		// }

		// outputStream.putFrame(mat);

	}

}

